apiVersion: v1
kind: Service
metadata:
  name: webapp-servicee
  labels:
    app:  mywebsite
    tire: frontend
spec:
    type: NodePort
    ports:
      - targetport: 8080
        port: 80
        nodeport: 30080
    selector:
      app:  simple-webapp



