apiVersion: v1
kind: Pod
metadata:
  name:myapp-pod
  labels:
    name: myapp-pod
    app: myapp
    type: pod

spec:
  containers:
    - name: nginx-image
      image: nginx


apiVersion: v1
kind: pod
metadata:
   name: postgres
   labels: tier
spec:
  containers:
  - name: postgres
    image: postgres